# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbdd7199c65d98c45c16a59261dfb4970dfcd5a96bd606130bda138ce03278077c5930d3d0084933d8db8ef0a4fdfda152ca56b3fe2488cc6996e620fb0cbc1d

test:
  secret_key_base: 26731509bab7e024b59bcc04c32866d0e23b79b89103a1607a1b2ca865b3c76019acb9082e869c95ff71c3379d6f01cf4237972bd4ba06e12d3e80a959189f77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
